export {default as LoginForm} from  './loginForm/loginForm.jsx'
export {default as AsideHeader} from  './AsideHeader/'
export {AsideContacts} from  './AsideContacts/'
export {default as MainHeader} from  './MainHeader/'
export {MainFooter} from  './MainFooter/'
export {Main} from  './Main/'
export {Chats} from  './Main/chats'
export {RecMes} from  './Main/RecMes/'
export {default as SentMes} from  './Main/SentMes/'
export {ChatContact} from './AsideContacts/ChatContact'
export {SearchContact} from './AsideHeader/SearchContact'
